### ISSUE TITLE
SSL/TLS errors when sending email.

### ISSUE THREAD

**Issue by gregotte** [shawnmclean/Mandrill-dotnet#109]
About 10% of the time we send an email it fails with the error below. I ended up implementing retry functionality as a work around, but it would be nice to know what causes this to happen.

System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult)
   at RestSharp.Http.RequestStreamCallback(IAsyncResult result, Action`1 callback)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Mandrill.MandrillApi.<ListTemplatesAsync>b__a2(Task`1 p)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at SMI.APICommon.MandrillEmailFactory.GetTemplateInfo(String name)
   at SMI.APICommon.MandrillEmailFactory.Send(MandrillSendMessagePayload payload)
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult)
   at RestSharp.Http.RequestStreamCallback(IAsyncResult result, Action`1 callback)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Mandrill.MandrillApi.<ListTemplatesAsync>b__a2(Task`1 p)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult)
   at RestSharp.Http.RequestStreamCallback(IAsyncResult result, Action`1 callback)<---
<---

**Comment by rishikapadia1** [comment]
It's happening for me as well and I also implemented retry logic, but it would be great if we know why a request is failing, Any luck @gregotte?
