### ISSUE TITLE
Exceptions are thrown when sending a message and IIS will restart

### ISSUE THREAD

**Issue by theoutlander** [shawnmclean/Mandrill-dotnet#156]
The messages are getting through just fine. However, the library throws some unhandled exception causing IIS to stop. I've also added an Unhandled Exception handler and I've tried task.continuewith as well as a synchronous call via wait (which hangs indefinitely). Any idea why this is happening?

Here's my call to Mandrill (the commented code is the async call). Also, none of the exceptions are thrown here:

    try
            {
                var msg = new EmailMessage
                {
                    To = new[]
                    {
                        string.IsNullOrWhiteSpace(toName)
                            ? new EmailAddress(toEmail)
                            : new EmailAddress(toEmail, toName)
                    },
                    FromName = fromName,
                    FromEmail = fromEmail,
                    Subject = subject
                };

                msg.AddGlobalVariable("CONTENT", message);
                
                var sendMessageTemplateRequest = new SendMessageTemplateRequest(msg, MailTemplate.Blank.ToString(), new List<TemplateContent>());
                //var task = Api.SendMessageTemplate(sendMessageTemplateRequest);

                //task.ContinueWith(t =>
                //{
                //    Logger.Instance.Error("Exception thrown in SendMail", t.Exception);
                //}, TaskContinuationOptions.OnlyOnFaulted);

                Api.SendMessageTemplate(sendMessageTemplateRequest).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                Logger.Instance.Error(e.Message, e);
            }

Studio shows an exception in TaskContinuation.cs:

![image](https://cloud.githubusercontent.com/assets/749084/9768938/ccc62cc2-56db-11e5-953d-58d1d8272a39.png)

Here's a stack trace from the app domain's unhandled exception handler:

System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>/LM/W3SVC/1/ROOT-5-130862922077096483</AppDomain><Exception><ExceptionType>System.NullReferenceException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Object reference not set to an instance of an object.</Message><StackTrace>   at System.Web.ThreadContext.AssociateWithCurrentThread(Boolean setImpersonationContext)
   at System.Web.HttpApplication.OnThreadEnterPrivate(Boolean setImpersonationContext)
   at System.Web.LegacyAspNetSynchronizationContext.CallCallbackPossiblyUnderLock(SendOrPostCallback callback, Object state)
   at System.Web.LegacyAspNetSynchronizationContext.CallCallback(SendOrPostCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task&amp;amp; currentTask)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.AwaitTaskContinuation.&amp;lt;ThrowAsyncIfNecessary&amp;gt;b__1(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()</StackTrace><ExceptionString>System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Web.ThreadContext.AssociateWithCurrentThread(Boolean setImpersonationContext)
   at System.Web.HttpApplication.OnThreadEnterPrivate(Boolean setImpersonationContext)
   at System.Web.LegacyAspNetSynchronizationContext.CallCallbackPossiblyUnderLock(SendOrPostCallback callback, Object state)
   at System.Web.LegacyAspNetSynchronizationContext.CallCallback(SendOrPostCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task&amp;amp; currentTask)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.AwaitTaskContinuation.&amp;lt;ThrowAsyncIfNecessary&amp;gt;b__1(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()</ExceptionString></Exception></TraceRecord>

**Comment by theoutlander** [comment]
The only other thing that I can think of is that I'm sending four emails back to back without using a queue at the moment.

**Comment by theoutlander** [comment]
It appears that the following line fixes the issue:
    
     List<EmailResult> result = await Api.SendMessageTemplate(sendMessageTemplateRequest);

I had tried ConfigureAwait(true) earlier and that hadn't worked either.
