### ISSUE TITLE
Gettting json parse error at line0pos0 while sending email

### ISSUE THREAD

**Issue by madhuadbanker** [shawnmclean/Mandrill-dotnet#210]
In continuation to issue#169
I am using 3.1.0 mandril version and i am still facing this issue. Can you please suggest me how to handle this?

My exception:
           Mandrill.Utilities.MandrillSerializationException: Failed to deserialize error content received from path: messages/send.json. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
  at Newtonsoft.Json.JsonTextReader.ParseValue()
  at Newtonsoft.Json.JsonTextReader.Read()
  at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
  at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
  at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
  at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
  at Mandrill.MandrillApi.ParseResponseContent[T](String path, RequestBase data, String content, HttpResponseMessage response)
  --- End of inner exception stack trace ---
  at Mandrill.MandrillApi.ParseResponseContent[T](String path, RequestBase data, String content, HttpResponseMessage response)
  at Mandrill.MandrillApi.<Post>d__11`1.MoveNext()

_Originally posted by @madhuadbanker in https://github.com/shawnmclean/Mandrill-dotnet/issue_comments#issuecomment-438496104_

**Comment by Elviszip** [comment]
still and issue ☝️
